### ISSUE TITLE
Game doesn't load [1.14.4]

### ISSUE THREAD

**Issue by MelanX** [MiningMark48/Tiered-Magnets#10]
**Version**
Forge: 28.1.70
Mod-version: 1.0.0

**Describe the bug**
![image](https://user-images.githubusercontent.com/26039509/67703771-4941f680-f9b4-11e9-8380-033222c6f552.png)
This is shown on startup.

**To Reproduce**
1. Setup the game with version like described before.
2. Try to start the game.

**Expected behavior**
Game loads

**Screenshots**
![image](https://user-images.githubusercontent.com/26039509/67703950-8e662880-f9b4-11e9-912a-3c134cd94a27.png)
Here we go again :D 

**Additional context**
latest. log: https://pastebin.com/UjCZp6xy

**Comment by MiningMark48** [comment]
This is fixed in an upcoming update as I updated Forge. Should be out soon. Thanks though!

**Comment by MiningMark48** [comment]
Fixed in this version for Forge 28.1.64 

https://www.curseforge.com/minecraft/mc-mods/tiered-magnets/files/2818283
