### ISSUE TITLE
langs are wrong

### ISSUE THREAD

**Issue by MelanX** [MiningMark48/Tiered-Magnets#11]
https://github.com/MiningMark48/Tiered-Magnets/tree/1.14.x/src/generated
This folder needs to be deleted. Or just replaced by resources. Each item looks like this: 
![image](https://user-images.githubusercontent.com/26039509/68203452-1dcb9700-ffc6-11e9-9c9b-8a8b7a314913.png)

No versions needed I guess :)

**Comment by MiningMark48** [comment]
Known and a fix is coming soon. `src/generated` folder is only relevant to an upcoming version as data generators aren't used in any currently released versions. Thanks though!

**Comment by MiningMark48** [comment]
Should be fixed in upcoming 1.16 version. No ETA.
