### ISSUE TITLE
"Crash" on server when crafting

### ISSUE THREAD

**Issue by MelanX** [MiningMark48/Tiered-Magnets#12]
**Version**
Tiered Magnets: 1.14.4-1.1.0
Forge: 28.1.90

**Describe the bug**
latest.log: https://pastebin.com/aXzrKu9k
If you craft a magnet on a server the player will be kicked from the server with an internal error message.
If you rejoin it's the same problem. If you edit the players inventory that the player does not have the magnet anymore, the player can join.

**To Reproduce**
1. Craft a magnet
2. get kicked

**Expected behavior**
no kick

If you need more information, please let me know

**Comment by MelanX** [comment]
Oh I forgot to say: I was crafting a magnet before putting the world on a server. This magnet worked fine on multiplayer.

**Comment by MelanX** [comment]
Sorry, clicked wrong button xD

**Comment by MiningMark48** [comment]
Should be fixed in upcoming 1.16 version. No ETA.
